module.exports = {
      name: 'joke',
      description: 'This command is for telling jokes',
      execute(message, args) {

var j = ["A man walks into a library and asks the librarian for books about paranoia. She whispers, \"They're right behind you!\"",
"Want to hear a roof joke? The first one's on the house.",
"What should you do if you're attacked by a group of clowns? Go straight for the juggler.",
"Why don't koalas count as bears? They don't have the right koalafications.",
"A cement mixer and a prison bus crashed on the highway. Police advise citizens to look out for a group of hardened criminals.",
"I couldn't figure out why the baseball kept getting bigger. Then it hit me.",
"I saw a movie about how ships are put together. It was riveting.";,
"A man walks into a library and orders a hamburger. The librarian says, \"This is a library.\" The man apologizes and whispers, \"I'd like a hamburger, please.\"",
"Why did the taxi driver get fired? Passengers didn't like it when she went the extra mile.",
"What do you get when you pour root beer into a square cup? Beer.",
"A group of crows was arrested for hanging out together. The charge? Attempted murder.",
"How do you look for Will Smith in the snow? Just follow the fresh prints.",
"Which rock group has four guys who can't sing or play instruments? Mount Rushmore.",
"Why does Humpty Dumpty love autumn? Because he always has a great fall.",
"Why does Humpty Dumpty love autumn? Because he always has a great fall.",
"Where do hamburgers take their sweethearts on Valentine's Day to dance? The Meat Ball!",
"What time does a duck wake up? The quack of down.",
"Some people eat snails. They must not like fast food.",
"Have you heard the one about the skunk? Never mind, it really stinks.",
"It's always windy in a sports arena. All those fans.",
"How do mountains stay warm in the winter? Snowcaps.",
"What happens to a frog's car when it breaks down? It gets toad away.",
"What do you call a pile of kittens? A meowntain.",
"Is this pool safe for diving? It deep ends.",
"What is worse than raining cats and dogs? Hailing taxis!",
"What did the nose say to the finger? Quit picking on me!",
"What is the best day to go to the beach? Sunday, of course!",
"What bow can't be tied? A rainbow!",
"How many tickles does it take to make an Octopus laugh? Ten-tickles.",
"How does a dog stop a video? By hitting the paws button!",
"People think \"icy\" is the easiest word to spell. Come to think of it, I see why.",
"My teachers told me I'd never amount to much because I procrastinate so much. I told them, \"Just you wait!\"",
"Comic Sans walks into a bar. The bartender says, \"We don't serve your type here.\"",
"What's the easiest way to get straight As? Use a ruler.",
"A grasshopper sits down at a bar. The bartender says, \"We have a drink named after you!\" The grasshopper replies, \"Who names a drink 'Steve?'\"",
"What's a balloon's least favorite type of music? Pop.I went into a store to buy some books about turtles. \"Hardbacks?\" asked the shopkeeper.\"Yes,\" I replied. \"And they have little heads, too.\"",
"I went into a store to buy some books about turtles. \"Hardbacks?\" asked the shopkeeper.\"Yes,\" I replied. \"And they have little heads, too.\"",
"What does the world's top dentist get? A little plaque.",
 "I used to be addicted to not showering. Luckily, I've been clean for five years.",
 "Have you heard about Murphy's Law? Yes. Anything that can go wrong will go wrong. How about Cole's Law? No. It's julienned cabbage in a creamy dressing.",
 "What did the green grape say to the purple grape? \"Breathe, man! Breathe!\"",
 "What's the difference between a hippo and a Zippo? One is really heavy, the other's a little lighter.",
"How does a farmer mend his overalls? With cabbage patches.",
"Why was the tomato red? Because he saw the salad dressing.",
"I got my husband a fridge for his birthday. His face lit up when he opened it.",
"Why were they called the Dark Ages? Because there were lots of knights.",
"How does NASA organize a party? They planet.",
"What did the big flower say to the little flower? Hi bud!",
"What's sticky and brown? A stick!",
"Why is no one friends with Dracula? Because he's a pain in the neck.",
"What did one toilet say to the other? You look flushed."];

            var joke_num = Math.ceil(Math.random()*j.length);

            console.log("Tell Joke called by " + message.author.tag + ", joke_num = " + joke_num);
            message.channel.send(j[joke_num])
      }
}
